service:
  port: "9091"
  port-grpc: "9090"
db:
  postgres:
    user: "root"
    password: "bRSvlQ6WXYKnIijwIPnp"
    host: "amole-database.c9kw2g80qxj7.ap-southeast-2.rds.amazonaws.com"
    port: 5432
    schema: "amole_db"
    min-conn: 10
    max-conn: 100
    max-life-time: 12s
    keep-alive-interval: 20s
security:
  jwt:
    secret: "acret123-812xliasfekaltasfesa231"
    access-time: 1d
